name: compose

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Check docker-compose file config 
        run: docker-compose -f ./compose/docker-compose.yml config
      
      - name: Docker Compose Action
        uses: isbang/compose-action@v0.1.1
        with: 
          compose-file: ./compose/docker-compose.yml
